name: master
on: 
  push:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 3.0.0
          bundler-cache: true

      - name: Install gems
        run: bundle install
        
      - name: Run RuboCop
        run: bundle exec rubocop
        
      - name: Run tests
        run: rake
